version: "3.9"
services:
  frontend:
    image: ghcr.io/vinay-hegde17/demoapp-frontend:latest
    ports:
      - "3030:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    image: ghcr.io/vinay-hegde17/demoapp-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://host.docker.internal:27017/testingdb
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: testingdb
    ports:
      - "27017:27017"
