version: "3.9"
services:
  frontend:
    build:
      context: ./sampleapp
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./samplenodeapp
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
