version: "3.9"
services:
  frontend:
    build:
      context: ./sampleapp
      dockerfile: Dockerfile
    ports:
      - "3030:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./samplenodeapp
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://db:27017/testingdb
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: testingdb
    ports:
      - "27017:27017"
