permissions:
  contents: write
  packages: write

name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sampleapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

  merge-to-main:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        run: |
          git checkout main
          git merge --ff-only dev || git merge dev --no-ff -m "Auto-merge dev into main [skip ci]"
          git push origin main

  sync-main-to-dev:
    needs: merge-to-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: dev

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Merge main back to dev
        run: |
          git checkout dev
          git merge main --no-ff -m "Sync main into dev [skip ci]"
          git push origin dev

  docker-build:
    needs: sync-main-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./sampleapp
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/demoapp-react:latest
            ghcr.io/${{ github.repository_owner }}/demoapp-react:${{ github.sha }}

      - name: Remove old local images
        run: docker image prune -af

      - name: Pull latest image to ensure local update
        run: docker pull ghcr.io/${{ github.repository_owner }}/demoapp-react:latest
